LaPirana/Models/Contacto.cs
namespace LaPirana.Models
{
    public class Contacto
    {
        public string Nombre {get;set;}
        public string Apellido {get;set;}
        public string Motivo {get;set;}
        public string Mensaje {get;set;}
    }
}

LaPirana/Models/ErrorViewModel.cs
using System;

namespace LaPirana.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LaPirana/Controllers/CompraController.cs
using Microsoft.AspNetCore.Mvc;

namespace LaPirana.Controllers
{
    public class CompraController: Controller
    {
        public IActionResult Pagar()
        {
            return View("Pagar");
        }
        public IActionResult Resumen()
        {
            return View("Resumen");
        }
    }
}

LaPirana/Controllers/CuentaController.cs
using Microsoft.AspNetCore.Mvc;

namespace LaPirana.Controllers
{
    public class CuentaController: Controller
    {
        public IActionResult Actualizar()
        {
            return View("Actualizar");
        }
        public IActionResult Iniciar()
        {
            return View("Iniciar");
        }
        public IActionResult Registro()
        {
            return View("Registro");
        }
    }
}

LaPirana/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using LaPirana.Models;

namespace LaPirana.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LaPirana/Controllers/PresentacionController.cs
using Microsoft.AspNetCore.Mvc;

namespace LaPirana.Controllers
{
    public class PresentacionController: Controller
    {
        [HttpGet]
        public IActionResult Contacto()
        {
            var mensaje = "Bienvenido a mi página";
            ViewData["Mensaje"] = mensaje;
            return View();
        }
        public IActionResult Servicios()
        {
            return View();
        }
        public IActionResult Somos()
        {
            return View();
        }
    }
}

LaPirana/Controllers/VentaController.cs
using Microsoft.AspNetCore.Mvc;

namespace LaPirana.Controllers
{
    public class VentaController: Controller
    {
        public IActionResult Catalogo()
        {
            return View();
        }
        public IActionResult ProductosDestacados()
        {
            return View();
        }
        public IActionResult Servicios()
        {
            return View();
        }
    }
}

LaPirana/Views/Compra/Pagar.cshtml
<h1>Página Compra / Pagar Compra</h1>

LaPirana/Views/Compra/Resumen.cshtml
<h1>Página Compra / Resumen de Compra</h1>

LaPirana/Views/Cuenta/Actualizar.cshtml
<h1>Página Cuenta / Actualizar Perfil</h1>

LaPirana/Views/Cuenta/Iniciar.cshtml
<h1>Página Cuenta / Iniciar Sesión</h1>

LaPirana/Views/Cuenta/Registro.cshtml
<h1>Página Cuenta / Registro</h1>

LaPirana/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LaPirana/Views/Presentacion/Contacto.cshtml
<h1>Página Presentación / Formulario de Contacto</h1>

<h2>@ViewData["Mensaje"]</h2>

<div class="form-group">
    <label for="">Nombre</label>
    <input class="form-control" type="text" name="" id="">
    <label for="">Apellido</label>
    <input class="form-control" type="text" name="" id="">
    <label for="">Motivo de contacto</label>
    <input class="form-control" type="text" name="" id="">
    <label for="">Mensaje</label>
    <input class="form-control" type="text" name="" id="">

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Registrar</button> 
    </div> 
</div>

LaPirana/Views/Presentacion/Servicios.cshtml
<h1>Página Presentación / Servicios y Productos</h1>

LaPirana/Views/Presentacion/Somos.cshtml
<h1>Página Presentación / Quiénes Somos</h1>

LaPirana/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LaPirana</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LaPirana</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item container border border-dark">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item container border border-dark">
                            <a class="nav-link text-danger" asp-area="" asp-controller="Presentacion" asp-action="Contacto">Contacto</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Presentacion" asp-action="Servicios">Servicios</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Presentacion" asp-action="Somos">Somos</a>
                        </li>
                        <li class="nav-item container border border-dark">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Venta" asp-action="Catalogo">Catálogo</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Venta" asp-action="ProductosDestacados">ProductosDestacados</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Venta" asp-action="Servicios">Servicios</a>
                        </li>
                        <li class="nav-item container border border-dark">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Compra" asp-action="Pagar">Pagar</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Compra" asp-action="Resumen">Resumen</a>
                        </li>
                        <li class="nav-item container border border-dark">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="Actualizar">Actualizar</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="Iniciar">Iniciar</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="Registro">Registro</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - LaPirana - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LaPirana/Views/Venta/Catalogo.cshtml
<h1>Página Venta / Catálogo Completo de Productos</h1>

LaPirana/Views/Venta/ProductosDestacados.cshtml
<h1>Página Venta / Productos Destacados</h1>

LaPirana/Views/Venta/Servicios.cshtml
<h1>Página Venta / Servicios</h1>